
function rgcliente() {
    document.getElementById("info").innerHTML = "h"
   +"<center>"
   +"<h1>SERVITECA SU SOLUCION AL INSTANTE</h1>"
    +"<form action='index.html' method='post'  style='width: 400px;'  >"
                +"<fieldset class='borde1'>"
                +"<legend>REGISTAR CLIENTE</legend>"
                +"<tr>"                  
                   + "<th><label for=''>NOMBRES</label></th><br>"
                   + "<th><input type='text' name='' id='' placeholder='escriba su nombre'></th><br><br>"
                   + "<th><label for=''>APELLIDOS</label></th><br>"
                   + "<th><input type='text' name='' id='' placeholder='escriba su apellido'></th>"
                +"</tr><br><br>"
                +"<tr>"
               +"<th><label for=''> Tipo Identificacion</label></th><br>"
                +"<th><select name='' id=''>"
                    +"<option value=''>Escoja una opcion</option>"
                    +"<option value=''>Cedula de Ciudadania</option>"
                    +"<option value=''>Tarjeta de Identificacion</option>"
                    +"<option value=''>Cedula de Extranjeria</option>"
                    +"<option value=''>Pasaporte</option>"
                +"</select></th><br><br>"
                +"<th><label for=''>NUMERO</label></th><br>"
                    +"<th><input type='text' name='' id='' placeholder='numero de cedula'></th><br><br>"
                    +"<th><label for=''>CORREO</label></th><br>"
                    +"<th><input type='email' name='' id='placeholder='escriba su correo' ></th><br><br>"
                    +"<th><label for=''>CELULAR</label></th><br>"
                    +"<th><input type='tel' name='' id='' placeholder='numero celular'></th><br><br>"
                +"</tr>"
                +"<tr>"
                    +"<th><input type='submit' value='INICIO'></th>"
                    +"<th><input type='submit' value='REGISTAR'></th>"
                +"</tr>"
            +"</fieldset>"
            +"</form> "
            +"</center>"
}

function rgcarro() {
    document.getElementById("info").innerHTML = ""
    +"<center>"
    +"<h1>SERVITECA SU SOLUCION AL INSTANTE</h1>"
+"<form action='index.html' method='post' style='width: 300px;'   >"
           +"<fieldset>"
                +"<legend>REGISTAR CARRO</legend>"
       +" <tr>"
            +"<th><label for=''>PLACA</label></th>"
            +"<th><input type='text'></th>"
       +" </tr> <br><br>"
        +"<tr>"
            +"<th><label for=''>MARCA</label></th>"
           +"<th><input type='text'></th>"
        +"</tr>    <br> <br>"
        
        +"<tr>"
            +"<th><label for=''>MODELO</label></th>"
            +"<th><input type='text'></th>"
        +"</tr>  <br><br>"
        +"<tr><input type='submit' value='REGISTAR'></tr>"
        +"</fieldset>"
        +"</form>"
        +"</center>"
    }
    function consulcarro() {
        document.getElementById("info").innerHTML = " "
        +"<center>"
        +"<h1>SERVITECA SU SOLUCION AL INSTANTE</h1>"
        +"<h2>CONSULTA CARROS</h2>"
+"<table id='customers'>"
  +"<tr>"
    +"<th>PLACA</th>"
    +"<th>MARCA</th>"
    +"<th>MODELO</th>"
  +"</tr>"
  +"<tr>"
   +"<td>CIM 942</td>"
   +"<td>MAZDA</td>"
    +"<td>2004</td>"
 +"</tr>"
  +"<tr>"
   +"<td>RCR 878</td>"
    +"<td>DODGE</td>"
    +"<td>2010</td>"
 +" </tr>"
  +"<tr>"
    +"<td>DFE 524</td>"
    +"<td>PORGCHE</td>"
    +"<td>2020</td>"
  +"</tr>"
  +"<tr>"
    +"<td>MFC 541</td>"
    +"<td>CHIN</td>"
    +"<td>2005</td>"
  +"</tr>"
  +"<tr>"
    +"<td>MRA 412</td>"
    +"<td>PAE</td>"
    +"<td>2009</td>"
 +"</tr>"
  +"<tr>"
    +"<td>TOY 125</td>"
    +"<td>TOYOTA</td>"
    +"<td>2022</td>"
 +"</tr>"
  
+"</table>"
+"<form>"
    +"<input type='text' name='buscar' placeholder='buscar carro '><br><br>"
   
+"</form>"
+"<form action='index.html' method='post'>"
    +"<input type='submit' value='INICIO'>"
+"</form>"
+"</center>"
    }

    function consulcliente() {
        document.getElementById("info").innerHTML = " "
        +"<center>"
        +"<h1>SERVITECA SU SOLUCION AL INSTANTE</h1>"
    +"<h1>CONSULTA CLIENTES</h1>"

+"<table id='customers'>"
  +"<tr>"
    +"<th>NOMBRE</th>"
    +"<th>APELLIDO</th>"
    +"<th>TP IDENTIFICACION</th>"
    +"<th>NUMERO</th>"
    +"<th>CORREO</th>"
    +"<th>CELULAR</th>"
  +"</tr>"
  +"<tr>"
    +"<td>LUIS</td>"
    +"<td>TRUJILLO</td>"
    +"<td>cc</td>"
    +"<td>1065611789</td>"
    +"<td>luis@gmail.com</td>"
    +"<td>3507258456</td>"
  +"</tr>"
  +"<tr>"
    +"<td>JOSE</td>"
    +"<td>RAMIREZ</td>"
    +"<td>cc</td>"
    +"<td>1068511789</td>"
    +"<td>JOSE@gmail.com</td>"
    +"<td>3007258456</td>"
 +"</tr>"
  +"<tr>"
    +"<td>JUAN</td>"
    +"<td>CARRILLO</td>"
    +"<td>cc</td>"
    +"<td>1065458789</td>"
    +"<td>JUAN134@gmail.com</td>"
    +"<td>3112458456</td>"
  +"</tr>"
  +"<tr>"
    +"<td>JHAROL</td>"
    +"<td>DORIA</td>"
    +"<td>cc</td>"
    +"<td>1075215789</td>"
    +"<td>J.D.12345@gmail.com</td>"
    +"<td>301758456</td>"
  +"</tr>"
  +"<tr>"
    +"<td>MARCO</td>"
    +"<td>TRILLO</td>"
    +"<td>cc</td>"
    +"<td>1002511789</td>"
    +"<td>MARCOT458@gmail.com</td>"
    +"<td>3107818456</td>"
  +"</tr>"
  +"<tr>"
    +"<td>LUIS</td>"
    +"<td>RAMIREZ</td>"
    +"<td>cc</td>"
    +"<td>100101789</td>"
    +"<td>luis558@gmail.com</td>"
    +"<td>3007258456</td>"
  +"</tr>"
  +"<tr>"
    +"<td>YULIETH</td>"
    +"<td>TRUJILLO</td>"
    +"<td>cc</td>"
    +"<td>77611789</td>"
    +"<td>YULIETHTRU@gmail.com</td>"
    +"<td>3207258456</td>"
  +"</tr>"
  
+"</table>"
+"<form>"
    +"<input type='text' name='buscar' placeholder='buscar clientes'><br><br>"
   
+"</form>"
+"<form action='index.html' method='post'>"
   +"<input type='submit' value'INICIO'>"
+"</form>"
+"</center>"

    }

function rgservicio() {
    document.getElementById("info").innerHTML = " "
    +"<center>"
    +"<h1>SERVITECA SU SOLUCION AL INSTANTE</h1>"
    +"<form action='index.html' method='post'  style='width: 400px;' >"
        +"<fieldset class='borde1'>"
        +"<legend>SERVICIOS</legend>"
        +"<tr>"
            
            +"<th><label for=''>NOMBRES Y APELLIDOS</label></th><br>"
            +"<th><input type='text' name='' id='' placeholder='escriba su nombre'></th><br><br>"
            +"<tr>"
        +"<th><label for=''> Tipo Identificacion</label></th><br>"
       +"<th><select name='' id=''>"
            +"<option value=''>Escoja una opcion</option>"
            +"<option value=''>Cedula de Ciudadania</option>"
            +"<option value=''>Tarjeta de Identificacion</option>"
            +"<option value=''>Cedula de Extranjeria</option>"
            +"<option value=''>Pasaporte</option>"
        +"</select></th><br><br>"
        ++ "<th><input type='text' name='' id='' Numero'></th><br><br>"
        +"<th><label for=''> Tipo de Servicio</label></th><br>"
        +"<th><select name='' id=''><br><br><br><br>"
            +"<option value=''>Escoja una opcion</option>"
            +"<option value=''>ALINEACION Y BALANCEO</option>"
            +"<option value=''>CAMBIO DE ACEITE</option>"
            +"<option value=''>MANTENIMINETO PREVENTIVO</option>"
            +"<option value=''>REPARACION MOTOR</option><br><br><br><br>"
            +"</select><br><br>"
            +"<th><label for=''>CORREO</label></th><br>"
            +"<th><input type='email' name='' id=''placeholder='escriba su correo' ></th><br><br>"
            +"<th><label for=''>CELULAR</label></th><br>"
            +"<th><input type='tel' name='' id='' placeholder='celular'></th><br><br>"
        +"</tr>"
        +"<tr>"
            +"<th><input type='submit' value='INICIO'></th>"
            +"<th><input type='submit' value='REGISTAR'></th>"
        +"</tr>"
    +"</fieldset>"
   +"</form>"
+"</center>"
}

function consulservi() {
  document.getElementById("info").innerHTML = " "
  +"<center>"
  +"<h1>SERVITECA SU SOLUCION AL INSTANTE</h1>"
+"<h1>CONSULTA SERVICIO</h1>"

+"<table id='customers'>"
+"<tr>"
+"<th>NOMBRE</th>"
+"<th>APELLIDO</th>"
+"<th>TP IDENTIFICACION</th>"
+"<th>NUMERO</th>"
+"<th>CORREO</th>"
+"<th>CELULAR</th>"
+"</tr>"
+"<tr>"
+"<td>LUIS</td>"
+"<td>TRUJILLO</td>"
+"<td>cc</td>"
+"<td>1065611789</td>"
+"<td>luis@gmail.com</td>"
+"<td>3507258456</td>"
+"</tr>"
+"<tr>"
+"<td>JOSE</td>"
+"<td>RAMIREZ</td>"
+"<td>cc</td>"
+"<td>1068511789</td>"
+"<td>JOSE@gmail.com</td>"
+"<td>3007258456</td>"
+"</tr>"
+"<tr>"
+"<td>JUAN</td>"
+"<td>CARRILLO</td>"
+"<td>cc</td>"
+"<td>1065458789</td>"
+"<td>JUAN134@gmail.com</td>"
+"<td>3112458456</td>"
+"</tr>"
+"<tr>"
+"<td>JHAROL</td>"
+"<td>DORIA</td>"
+"<td>cc</td>"
+"<td>1075215789</td>"
+"<td>J.D.12345@gmail.com</td>"
+"<td>301758456</td>"
+"</tr>"
+"<tr>"
+"<td>MARCO</td>"
+"<td>TRILLO</td>"
+"<td>cc</td>"
+"<td>1002511789</td>"
+"<td>MARCOT458@gmail.com</td>"
+"<td>3107818456</td>"
+"</tr>"
+"<tr>"
+"<td>LUIS</td>"
+"<td>RAMIREZ</td>"
+"<td>cc</td>"
+"<td>100101789</td>"
+"<td>luis558@gmail.com</td>"
+"<td>3007258456</td>"
+"</tr>"
+"<tr>"
+"<td>YULIETH</td>"
+"<td>TRUJILLO</td>"
+"<td>cc</td>"
+"<td>77611789</td>"
+"<td>YULIETHTRU@gmail.com</td>"
+"<td>3207258456</td>"
+"</tr>"

+"</table>"
+"<form>"
+"<input type='text' name='buscar' placeholder='buscar clientes'><br><br>"

+"</form>"
+"<form action='index.html' method='post'>"
+"<input type='submit' value'INICIO'>"
+"</form>"
+"</center>"

}